---

apiVersion: v1
kind: Service
metadata:
  name: development-cloudstack-svc
  namespace: cloudstack
  
spec:
  ports:
  - name: development-cloudstack-svc
    port: 8080
    protocol: TCP
    targetPort: 8080

  - name: development-cloudstack-svc-0
    port: 8250
    protocol: TCP
    targetPort: 8250

  selector:
    app: development-cloudstack
  sessionAffinity: None


