---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: cloudstack-db-pvc
  namespace: cloudstack
  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
status: {}


