---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: bzrcms-development-db-pvc
  namespace: bzrcms-development
  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
status: {}


