---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: bzrcms-development
  
spec:
  ports:
  - name: db
    port: 3306
    protocol: TCP
    targetPort: 3306

  selector:
    app: development-db-db
  sessionAffinity: None
