#!/bin/bash



#  --------------CENTOS BOX-----------

# UPDATE && UPGRADE
sudo yum -y update && sudo yum -y upgrade

# KVM & QEMU
sudo yum -y install epel-release
sudo yum -y install libvirt qemu-kvm virt-install virt-top libguestfs-tools bridge-utils kvm
# WHAT DID WE MISS?
sudo yum -y install qemu-kvm libvirt virt-install bridge-utils libvirt-devel  libxslt-devel libxml2-devel libvirt-devel libguestfs-tools-c


# ADDITIONAL 
sudo yum -y install git


sudo lsmod | grep kvm
#kvm_intel 147785 0
#kvm 464964 1 kvm_intel


# INSTALL DOCKER 
curl -fsSL https://get.docker.com/ | sh
sudo systemctl start docker


# SPIN UP VIRTUAL MACHINES TO KUBE SPRAY 
git clone https://github.com/kubernetes-sigs/kubespray.git 


# https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.rpm
curl https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.rpm | sudo rpm -iU
# need for vagrant kvm
sudo yum install ruby-devel.x86_64
#sudo vagrant plugin install vagrant-kvm 
sudo vagrant plugin install vagrant-libvirt

# OUR BOX NEEDS IP FORWARDING

echo "net.ipv4.ip_forward = 1"|sudo tee /etc/sysctl.d/99-ipforward.conf
sysctl -p /etc/sysctl.d/99-ipforward.conf

systemctl enable libvirtd
systemctl start libvirtd

# WE WANT THIS TO BE SET TO LIBVIRTD
VAGRANT_DEFAULT_PROVIDER="libvirt"
