#!/bin/bash



#  --------------CENTOS BOX-----------

# UPDATE && UPGRADE
sudo yum -y update && sudo yum -y upgrade

# KVM & QEMU
sudo yum -y install epel-release
sudo yum -y install libvirt qemu-kvm virt-install virt-top libguestfs-tools bridge-utils kvm

# ADDITIONAL 
sudo yum -y install git


sudo lsmod | grep kvm
#kvm_intel 147785 0
#kvm 464964 1 kvm_intel


# INSTALL DOCKER 
curl -fsSL https://get.docker.com/ | sh
sudo systemctl start docker


# SPIN UP VIRTUAL MACHINES TO KUBE SPRAY 
sudo useradd godmode
WD="/home/godmode"
sudo mkdir -p $WD
cd $WD

sudo su godmode -c git clone https://github.com/kubernetes-sigs/kubespray.git $WD/kubespray



