#!/bin/bash

whatweant="tcpdump"
pm=""

if [ -f /etc/os-release ]; then
    OS=$NAME
    VER=$VERSION_ID

elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)

elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE

elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
    pm="apt install -y"

elif [ -f /etc/SuSe-release ]; then
    echo 'suse'

elif [ -f /etc/redhat-release ]; then
    pm="yum install -y"
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=$(uname -s)
    VER=$(uname -r)
fi


if [[ $pm ]]; then
$pm $whatwewant;
fi
