#!/bin/bash

#https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script
function os_type
{
case `uname` in
  Linux )
     LINUX=1
     which yum && { sudo yum install -y  tcpdump;  }
     which zypper && { echo opensuse; }
     which apt-get && { sudo apt install -y tcpdump; }
     ;;
  Darwin )
     DARWIN=1
     ;;
  * )
     # Handle AmgiaOS, CPM, and modified cable modems here.
     ;;
esac

}  


os_type
