#!/bin/bash

whatweant="tcpdump"
pm=""

yum='yum install -y ' 
apt='apt install -y '

#https://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script
function os_type
{
case `uname` in
  Linux )
     LINUX=1
     which yum && { echo $yum; return; }
     which zypper && { echo opensuse; return; }
     which apt-get && { echo $apt; return; }
     ;;
  Darwin )
     DARWIN=1
     ;;
  * )
     # Handle AmgiaOS, CPM, and modified cable modems here.
     ;;
esac

}  



$(os_type) $whatwewant
